version: '3'
services:

  nginx: 
    image: nginx:latest
    container_name: sgn-nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/mime.types:/etc/nginx/mime.types
      - ${CERT_DIR}:/etc/letsencrypt/live/shanegriffin.net/
      - ${DATA_PATH}/public:/var/www/public
      - ${DATA_PATH}/images:/var/www/images
    ports:
      - "80:80"
      - "443:443"

  sgn:
    image: sgn-backend
    container_name: sgn-backend
    environment: 
      - API_KEY=${API_KEY}
      - IMAGES_PATH=/usr/src/data/images
      - DATABASE_URL=/usr/src/data/database.db
      - BIND_ADDRESS=0.0.0.0
    volumes:
      - ${DATA_PATH}:/usr/src/data
    ports:
      - "8080:8080"
