version: '3'
services:

  proxy: 
    image: nginx:latest
    container_name: proxy
    volumes:
      - ./nginx-${ENVIRONMENT}.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
      - "443:443"

  sgn:
    image: sgn-backend
    container_name: sgn
    environment: 
      - IMAGES_PATH=/usr/src/data/images
      - PUBLIC_PATH=/usr/src/data/public
      - DATABASE_URL=/usr/src/data/database.db
      - BIND_ADDRESS=0.0.0.0
    volumes:
      - ${DATA_PATH}:/usr/src/data
    ports:
      - "8080:8080"
